### ISSUE TITLE
frozen startup

### ISSUE THREAD

**Issue by Dat-cool-guy** [ScarecrowKrone/MineTek#222] opened 2015-04-06 03:27 UTC
Whenever I startup minetek, it freezes at this screen:
![frozen startup](https://cloud.githubusercontent.com/assets/8381925/7000168/10b062f8-dbea-11e4-8244-f7fc2cea6cc2.PNG)

I was using java 8 but then i tried downgrading to java 7 u76.

I've launched other modpacks and they work fine. I've also tried restarted my computer and nothing.

**Comment by skwerlman** [comment] 2015-04-06 04:33
How long do you let it sit for? Depending on your specs, it can take quite
a while to load (and windows will incorrectly say not responding)

If it's crashing, however, we'll need all the info requested in
CONTRIBUTING.md

**Comment by Dat-cool-guy** [comment] 2015-04-06 21:53
INFO:
OS: windows 7
java: 7 u76
pack version: 3.1.8

I let it sit for around an hour, My computer is not the best but usually loads minetek in about 10 to 20 mins (estimated).

**Comment by Dat-cool-guy** [comment] 2015-04-07 03:15
I tried letting it load longer to see if it goes anywhere and its been stuck at the same screen for over 3 hours now.

**Comment by skwerlman** [comment] 2015-04-07 09:50
Back up any local worlds from your Minetek folder, then delete your Minetek
folder and reinstall. Hopefully that will work.
If it doesn't, upload the latest forge log to paste.ubuntu.com

**Comment by Dat-cool-guy** [comment] 2015-04-07 13:38
where do i find the forge log if it doesn't work?

**Comment by Dat-cool-guy** [comment] 2015-04-07 13:54
I think this is it: http://paste.ubuntu.com/10762405/

**Comment by Dat-cool-guy** [comment] 2015-04-09 22:36
hey skwerlman, have you found the problem?

**Comment by skwerlman** [comment] 2015-04-15 13:27
Sorry for the late reply; I've been on vacation for a while.

It looks as though mekanism is crashing, but it hangs before it writes the
stack trace to the log...
Honestly, I've got no idea what the hang is caused by, since mekanism isn't
mentioned in the context of an error until the last two lines, which act as
though the error happened prior to them being written.

@scarecrowkrone, @ollieread: can you guys take a look at this? I'm stumped.

**Comment by ScarecrowKrone** [comment] 2015-05-31 09:57
It's been a very long time since I checked this place last, so forgive the massive waste for an answer. You are indeed correct skwerl, it's Mekanism. The system has hung because FML has skipped initialization for Mekanism but the system won't continue without it. This is likely because the jar files are corrupt. Also, it could possibly be related to a long since fixed Mekanism where the dependencies didn't point to where they should, a bit like closing a bridge over a river and not telling the people on the other side where the nearest alternative bridge is. Either way, it won't happen in the newest versions.

**Closed by ScarecrowKrone** 2015-05-31 09:57 UTC
Labels: unsolved
